[project]
name = "edeip"
version = "0.1.0"
description = "Example code"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.3",
    "pyside6>=6.8.2.1",
    "scipy>=1.15.2",
]

[tool.uv]
index-url = "https://mirrors.ustc.edu.cn/pypi/simple"
